#source and credits to MIT
from sec_edgar_downloader import Downloader

# the current working directory.
dl = Downloader(r"C:\Users\sbajwa\Box\Syndication\Market Landscape\Bajwa Code\REIT Bin Downloader")

# Get all 10-Q filings for 8 Previous Quarters as of 1/3/2023 for a REIT Comparative Market Analysis for REPE
dl.get("10-Q","ABR",amount=8)
dl.get("10-Q","ACR",amount=8)
dl.get("10-Q","ACRE",amount=8)
dl.get("10-Q","AGNC",amount=8)
dl.get("10-Q","AJX",amount=8)
dl.get("10-Q","AOMR",amount=8)
dl.get("10-Q","ARI",amount=8)
dl.get("10-Q","ARR",amount=8)
dl.get("10-Q","BRMK",amount=8)
dl.get("10-Q","BXMT",amount=8)
dl.get("10-Q","CHMI",amount=8)
dl.get("10-Q","CIM",amount=8)
dl.get("10-Q","CMTG",amount=8)
dl.get("10-Q","DX",amount=8)
dl.get("10-Q","EARN",amount=8)
dl.get("10-Q","EFC",amount=8)
dl.get("10-Q","GPMT",amount=8)
dl.get("10-Q","HASI",amount=8)
dl.get("10-Q","IVR",amount=8)
dl.get("10-Q","KREF",amount=8)
dl.get("10-Q","LADR",amount=8)
dl.get("10-Q","LFT",amount=8)
dl.get("10-Q","LOAN",amount=8)
dl.get("10-Q","MFA",amount=8)
dl.get("10-Q","MITT",amount=8)
dl.get("10-Q","NLY",amount=8)
dl.get("10-Q","NREF",amount=8)
dl.get("10-Q","NRZ",amount=8)
dl.get("10-Q","NYMT",amount=8)
dl.get("10-Q","ORC",amount=8)
dl.get("10-Q","PMT",amount=8)
dl.get("10-Q","RC",amount=8)
dl.get("10-Q","REFI",amount=8)
dl.get("10-Q","RWT",amount=8)
dl.get("10-Q","SACH",amount=8)
dl.get("10-Q","STAR",amount=8)
dl.get("10-Q","STWD",amount=8)
dl.get("10-Q","TRTX",amount=8)
dl.get("10-Q","TWO",amount=8)
dl.get("10-Q","WMC",amount=8)

##srb154@georgetown.edu